export const exditions = [
  {
    firm: 'Ulusoy',
    time: '10:00',
    seats: [
      { num: 1, gender: 'male' },
      { num: 2, gender: 'empty' },
      { num: 3, gender: 'female' },
      { num: 4, gender: 'empty' },
      { num: 5, gender: 'male' },
      { num: 6, gender: 'female' },
      { num: 7, gender: 'female' },
      { num: 8, gender: 'empty' },
      { num: 9, gender: 'empty' },
      { num: 10, gender: 'empty' },
      { num: 11, gender: 'male' },
      { num: 12, gender: 'male' },
      { num: 13, gender: 'female' },
      { num: 14, gender: 'male' },
      { num: 15, gender: 'male' },
      { num: 16, gender: 'female' },
      { num: 17, gender: 'empty' },
      { num: 18, gender: 'empty' },
      { num: 19, gender: 'male' },
      { num: 20, gender: 'empty' },
      { num: 21, gender: 'empty' },
      { num: 22, gender: 'female' },
      { num: 23, gender: 'male' },
      { num: 24, gender: 'empty' },
      { num: 25, gender: 'empty' },
      { num: 26, gender: 'female' },
      { num: 27, gender: 'male' },
      { num: 28, gender: 'empty' },
      { num: 29, gender: 'empty' },
      { num: 30, gender: 'male' },
    ],
    price: 450,
  },
  {
    firm: 'Metro',
    time: '14:00',
    seats: [
        { num: 1, gender: 'male' },
        { num: 2, gender: 'empty' },
        { num: 3, gender: 'female' },
        { num: 4, gender: 'empty' },
        { num: 5, gender: 'male' },
        { num: 6, gender: 'female' },
        { num: 7, gender: 'female' },
        { num: 8, gender: 'male' },
        { num: 9, gender: 'male' },
        { num: 10, gender: 'empty' },
        { num: 11, gender: 'male' },
        { num: 12, gender: 'male' },
        { num: 13, gender: 'female' },
        { num: 14, gender: 'empty' },
        { num: 15, gender: 'male' },
        { num: 16, gender: 'female' },
        { num: 17, gender: 'female' },
        { num: 18, gender: 'female' },
        { num: 19, gender: 'male' },
        { num: 20, gender: 'empty' },
        { num: 21, gender: 'empty' },
        { num: 22, gender: 'female' },
        { num: 23, gender: 'male' },
        { num: 24, gender: 'empty' },
        { num: 25, gender: 'empty' },
        { num: 26, gender: 'female' },
        { num: 27, gender: 'male' },
        { num: 28, gender: 'empty' },
        { num: 29, gender: 'empty' },
        { num: 30, gender: 'male' },
    ],
    price: 480,
  },
  {
    firm: 'Kamil Koç',
    time: '15:30',
    seats: [
        { num: 1, gender: 'male' },
        { num: 2, gender: 'empty' },
        { num: 3, gender: 'female' },
        { num: 4, gender: 'empty' },
        { num: 5, gender: 'male' },
        { num: 6, gender: 'female' },
        { num: 7, gender: 'female' },
        { num: 8, gender: 'empty' },
        { num: 9, gender: 'empty' },
        { num: 10, gender: 'empty' },
        { num: 11, gender: 'male' },
        { num: 12, gender: 'male' },
        { num: 13, gender: 'female' },
        { num: 14, gender: 'male' },
        { num: 15, gender: 'male' },
        { num: 16, gender: 'female' },
        { num: 17, gender: 'empty' },
        { num: 18, gender: 'empty' },
        { num: 19, gender: 'male' },
        { num: 20, gender: 'empty' },
        { num: 21, gender: 'empty' },
        { num: 22, gender: 'empty' },
        { num: 23, gender: 'male' },
        { num: 24, gender: 'empty' },
        { num: 25, gender: 'female' },
        { num: 26, gender: 'empty' },
        { num: 27, gender: 'male' },
        { num: 28, gender: 'empty' },
        { num: 29, gender: 'empty' },
        { num: 30, gender: 'male' },
    ],
    price: 420,
  },
  {
    firm: 'Ulusoy',
    time: '18:20',
    seats: [
        { num: 1, gender: 'female' },
        { num: 2, gender: 'empty' },
        { num: 3, gender: 'female' },
        { num: 4, gender: 'empty' },
        { num: 5, gender: 'male' },
        { num: 6, gender: 'female' },
        { num: 7, gender: 'empty' },
        { num: 8, gender: 'empty' },
        { num: 9, gender: 'empty' },
        { num: 10, gender: 'female' },
        { num: 11, gender: 'male' },
        { num: 12, gender: 'male' },
        { num: 13, gender: 'female' },
        { num: 14, gender: 'male' },
        { num: 15, gender: 'male' },
        { num: 16, gender: 'female' },
        { num: 17, gender: 'empty' },
        { num: 18, gender: 'female' },
        { num: 19, gender: 'male' },
        { num: 20, gender: 'empty' },
        { num: 21, gender: 'empty' },
        { num: 22, gender: 'empty' },
        { num: 23, gender: 'male' },
        { num: 24, gender: 'male' },
        { num: 25, gender: 'male' },
        { num: 26, gender: 'female' },
        { num: 27, gender: 'male' },
        { num: 28, gender: 'empty' },
        { num: 29, gender: 'empty' },
        { num: 30, gender: 'male' },
    ],
    price: 490,
  },
  {
    firm: 'Metro',
    time: '20:20',
    seats: [
        { num: 1, gender: 'male' },
        { num: 2, gender: 'empty' },
        { num: 3, gender: 'empty' },
        { num: 4, gender: 'empty' },
        { num: 5, gender: 'male' },
        { num: 6, gender: 'female' },
        { num: 7, gender: 'female' },
        { num: 8, gender: 'empty' },
        { num: 9, gender: 'empty' },
        { num: 10, gender: 'empty' },
        { num: 11, gender: 'male' },
        { num: 12, gender: 'male' },
        { num: 13, gender: 'female' },
        { num: 14, gender: 'empty' },
        { num: 15, gender: 'male' },
        { num: 16, gender: 'female' },
        { num: 17, gender: 'female' },
        { num: 18, gender: 'empty' },
        { num: 19, gender: 'male' },
        { num: 20, gender: 'empty' },
        { num: 21, gender: 'empty' },
        { num: 22, gender: 'empty' },
        { num: 23, gender: 'male' },
        { num: 24, gender: 'empty' },
        { num: 25, gender: 'empty' },
        { num: 26, gender: 'female' },
        { num: 27, gender: 'male' },
        { num: 28, gender: 'empty' },
        { num: 29, gender: 'empty' },
        { num: 30, gender: 'male' },
    ],
    price: 390,
  },
  {
    firm: 'Kamil Koç',
    time: '22:10',
    seats: [
        { num: 1, gender: 'male' },
        { num: 2, gender: 'empty' },
        { num: 3, gender: 'female' },
        { num: 4, gender: 'empty' },
        { num: 5, gender: 'male' },
        { num: 6, gender: 'female' },
        { num: 7, gender: 'female' },
        { num: 8, gender: 'empty' },
        { num: 9, gender: 'male' },
        { num: 10, gender: 'empty' },
        { num: 11, gender: 'male' },
        { num: 12, gender: 'empty' },
        { num: 13, gender: 'female' },
        { num: 14, gender: 'male' },
        { num: 15, gender: 'male' },
        { num: 16, gender: 'female' },
        { num: 17, gender: 'male' },
        { num: 18, gender: 'empty' },
        { num: 19, gender: 'male' },
        { num: 20, gender: 'empty' },
        { num: 21, gender: 'male' },
        { num: 22, gender: 'female' },
        { num: 23, gender: 'male' },
        { num: 24, gender: 'empty' },
        { num: 25, gender: 'empty' },
        { num: 26, gender: 'female' },
        { num: 27, gender: 'male' },
        { num: 28, gender: 'empty' },
        { num: 29, gender: 'empty' },
        { num: 30, gender: 'male' },
    ],
    price: 540,
  },
];
